# Generated by Django 3.2.5 on 2021-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210729_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(default='', upload_to='shop/ban')),
                ('slider_name', models.CharField(default="slider:<class 'django.db.models.fields.AutoField'>", max_length=20)),
                ('slider_label', models.CharField(max_length=50)),
                ('slider_label_sub', models.CharField(max_length=50)),
            ],
        ),
    ]
