# Generated by Django 3.2.5 on 2021-07-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_label_sub',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_name',
            field=models.CharField(default="slider<class 'django.db.models.fields.AutoField'>", max_length=100),
        ),
    ]
