# Generated by Django 3.2.5 on 2021-07-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210730_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='slider_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
