# Generated by Django 3.2.6 on 2021-08-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_slider_slider_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('Email', models.CharField(default='', max_length=100)),
                ('Gender', models.CharField(default='', max_length=100)),
                ('area', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
