# Generated by Django 3.2.6 on 2021-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='area',
        ),
        migrations.AddField(
            model_name='contact',
            name='Message',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
