# Generated by Django 3.2.6 on 2021-08-30 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20210818_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(default='', max_length=500)),
                ('Last_name', models.CharField(default='', max_length=500)),
                ('Phone', models.CharField(default='', max_length=1000)),
                ('Email', models.CharField(default='', max_length=500)),
                ('Address', models.CharField(default='', max_length=100)),
                ('Address2', models.CharField(default='', max_length=1000)),
                ('Country', models.CharField(default='', max_length=1000)),
                ('State', models.CharField(default='', max_length=1000)),
                ('Pin_code', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
