# Generated by Django 3.2.6 on 2021-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='First_name',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
