# Generated by Django 3.2.6 on 2021-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20210830_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Itemjson',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
