# Generated by Django 3.2.6 on 2021-08-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_orders_itemjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Trackid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
