# Generated by Django 3.2.6 on 2021-09-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_orders_trackid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders_update',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('Trackid', models.CharField(default='', max_length=500)),
                ('Detail', models.CharField(default='', max_length=5000)),
                ('Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
