# Generated by Django 3.2.6 on 2021-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_orders_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_update',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
