# Generated by Django 3.2.6 on 2021-09-01 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_rename_time_orders_update_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_update',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
