# Generated by Django 3.2.6 on 2021-09-01 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_orders_update_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_update',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
