# Generated by Django 3.2.6 on 2021-09-01 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_orders_update_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders_update',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='orders_update',
            name='pub_dates',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
