# Generated by Django 3.2.6 on 2021-09-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210901_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders_update',
            old_name='pub_dates',
            new_name='date_time',
        ),
    ]
