# Generated by Django 3.2.6 on 2021-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_pub_dates_orders_update_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_update',
            name='First_name',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
        migrations.AddField(
            model_name='orders_update',
            name='Last_name',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Trackid',
            field=models.CharField(default='', editable=False, max_length=500),
        ),
    ]
