# Generated by Django 3.2.6 on 2021-09-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20210901_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_update',
            name='First_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Last_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Trackid',
            field=models.CharField(default='', max_length=500),
        ),
    ]
