# Generated by Django 3.2.6 on 2021-09-02 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_orders_update_shipped_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_update',
            name='Arriving_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='orders_update',
            name='Arriving_order',
            field=models.CharField(choices=[('n', 'Choices'), ('at', 'Arriving')], default='n', max_length=4),
        ),
        migrations.AddField(
            model_name='orders_update',
            name='Out_for_delivery',
            field=models.CharField(choices=[('n', 'Choices'), ('ofd', 'Out for delivery')], default='n', max_length=4),
        ),
        migrations.AddField(
            model_name='orders_update',
            name='out_date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='shipped_order',
            field=models.CharField(choices=[('n', 'Choices'), ('syo', 'Shipped your order')], default='n', max_length=4),
        ),
    ]
