# Generated by Django 3.2.6 on 2021-09-02 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20210902_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_update',
            name='Arriving_order',
            field=models.CharField(choices=[('Choices', 'Choices'), ('Arriving', 'Arriving')], default='Choices', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Out_for_delivery',
            field=models.CharField(choices=[('Choices', 'Choices'), ('Out for delivery', 'Out for delivery')], default='Choices', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='shipped_order',
            field=models.CharField(choices=[('Choices', 'Choices'), ('Shipped your order', 'Shipped your order')], default='Choices', max_length=20),
        ),
    ]
