# Generated by Django 3.2.6 on 2021-09-03 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20210902_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='msg_id',
            new_name='ord_id',
        ),
        migrations.RenameField(
            model_name='orders_update',
            old_name='msg_id',
            new_name='ordup_id',
        ),
        migrations.AddField(
            model_name='orders_update',
            name='Delivered_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 15, 22, 748578)),
        ),
        migrations.AddField(
            model_name='orders_update',
            name='Delivered_order',
            field=models.CharField(choices=[('Choices', 'Choices'), ('order Delivered', 'order Delivered')], default='Choices', max_length=20),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Arriving_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 15, 22, 748578)),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Today_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 15, 22, 748578)),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='out_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 15, 22, 748578)),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='shipped_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 15, 22, 748578)),
        ),
    ]
