# Generated by Django 3.2.6 on 2021-09-03 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20210903_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders_update',
            name='Arriving_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 19, 4, 823043)),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Delivered_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 19, 4, 823043)),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='Today_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 19, 4, 823043)),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='out_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 19, 4, 823043)),
        ),
        migrations.AlterField(
            model_name='orders_update',
            name='shipped_date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 3, 13, 19, 4, 823043)),
        ),
    ]
