# Generated by Django 3.2.6 on 2021-09-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_payment_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment_Details',
        ),
    ]
