# Generated by Django 3.2.6 on 2021-09-03 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='Payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders'),
        ),
    ]
