# Generated by Django 3.2.6 on 2021-09-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_auto_20210903_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_details',
            old_name='order',
            new_name='porder',
        ),
    ]
