# Generated by Django 3.2.6 on 2021-09-03 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_rename_order_payment_details_porder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_details',
            name='Payment_id',
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='porder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shop.orders'),
        ),
    ]
