# Generated by Django 3.2.6 on 2021-09-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_auto_20210903_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_details',
            name='First_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Last_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='Payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='porder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orders'),
        ),
    ]
