# Generated by Django 3.2.5 on 2021-09-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=500)),
                ('First_name', models.CharField(max_length=500)),
                ('Last_name', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=500)),
                ('Phone', models.CharField(max_length=500)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=500)),
                ('Address', models.TextField(max_length=10000)),
            ],
        ),
    ]
