# Generated by Django 3.2.5 on 2021-09-11 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersignuplogin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDt',
        ),
    ]
