# Generated by Django 3.2.5 on 2021-09-11 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersignuplogin', '0002_rename_user_userdt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDt',
            new_name='UserProfile',
        ),
    ]
