# Generated by Django 3.2.5 on 2021-09-11 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersignuplogin', '0003_rename_userdt_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Country',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='State',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Address',
            field=models.CharField(max_length=10000),
        ),
    ]
