# Generated by Django 3.2.5 on 2021-09-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersignuplogin', '0004_auto_20210911_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=500),
        ),
    ]
