# Generated by Django 3.2.5 on 2021-09-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersignuplogin', '0006_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
