# Generated by Django 3.2.5 on 2021-09-16 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersignuplogin', '0009_auto_20210913_0606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
