# Generated by Django 3.2.5 on 2021-09-17 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0002_auto_20210917_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitems',
            name='Track_id',
        ),
        migrations.RemoveField(
            model_name='productitems',
            name='user',
        ),
    ]
