# Generated by Django 3.2.5 on 2021-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0005_auto_20210918_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProdectitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_name', models.CharField(max_length=1000)),
                ('P_qty', models.IntegerField(null=True)),
                ('P_price', models.IntegerField(null=True)),
                ('userorder', models.ManyToManyField(to='userdetails.UserOrder')),
            ],
        ),
    ]
