# Generated by Django 3.2.5 on 2021-09-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdetails', '0008_userprodectitems_track_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='Status',
            field=models.CharField(choices=[('Pending)', 'Pending'), ('Out Of Dilivery', 'Out Of Dilivery'), ('Order delivered', 'Order delivered')], default='Pending', max_length=500),
        ),
    ]
